### ISSUE TITLE
--list runtime exception if virtualenv directory is missing

### ISSUE THREAD

**Issue by ijanos** [sashahart/vex#34]
After a fresh install of vex I tried the `vex --list` but it threw `FileNotFoundError: [Errno 2] No such file or directory: '/home/USER/.virtualenvs' `

This is correct of course, because there is no such directory but maybe vex should catch this and show an appropriate message.

**Comment by sashahart** [comment]
Thanks for the catch. The message can be on stderr to avoid confusing tools which are splitting --list output on stdout. Are you capable of running and giving feedback on https://github.com/sashahart/vex/pull/36?

**Comment by ijanos** [comment]
Hi! Just tested it, works perfectly.

**Comment by sashahart** [comment]
Thank you for doing that, although I always do it myself I like to have independent eyeballs.

I've now added some tests and merged to master. I may wait a short while to do a new public version on PyPI.
