### ISSUE TITLE
pip "editable" installs to <cwd>/src directory

### ISSUE THREAD

**Issue by stianpr** [sashahart/vex#39]
When having an active shell doing: `pip install -e git+http://repo/my_project.git#egg=SomeProject` installs the package to `src` in my current working directory. Shouldn't it be installed to the virtual env directory? This is how it works with `pyvenv`. Maybe my setup is wrong?

**Comment by sashahart** [comment]
pip is using its environment to decide where to put things. If your environment got messed up e.g. by a .bashrc, this will happen. All vex can do is set the environment for the process it runs. If that process is a shell and decides to change the environment that you are using when you run pip from that shell, there is no mechanism vex can use to override the shell. You can try using vex pip and you can look at your shell environment.
