### ISSUE TITLE
After upgrading virtualenv (13.0.1) I get a warning _markerlib

### ISSUE THREAD

**Issue by aristidesfl** [sashahart/vex#42]
I now get this error when I use vex:

```
/usr/local/bin/vex:5: UserWarning: Module _markerlib was already imported from /Library/Python/2.7/site-packages/distribute-0.6.49-py2.7.egg/_markerlib/__init__.pyc, but /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python is being added to sys.path
  from pkg_resources import load_entry_point
```

Any ideas?

**Comment by sashahart** [comment]
I don't know from this what you are doing. vex doesn't use _markerlib. Literally, the message is coming from the process launched by vex, not from vex. Your error message suggests this is coming from pkg_resources and has something to do with distribute.
